server:
  port: 9090
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.94.193:3306/mytest?serverTimezone=UTC
    username: root
    password: ww214356ww
    schema: classpath*:sql/sql.sql
    initialization-mode: always
    dbcp2:
      max-idle: 20
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5


